config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  root 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'login', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'
  post 'messages', to: 'messages#create'
  resources :users, except: [:show, :edit]
  resources :chatrooms, only: [:index, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :members, dependent: :destroy
  belongs_to :creater, class_name: "User"

end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  scope :conversations, -> {
    joins("LEFT JOIN chatrooms ON members.chatroom_id = chatrooms.id")
      .joins("LEFT JOIN messages ON chatrooms.last_message_id = messages.id")
      .preload(:user)
      .select(" members.user_id,
                chatrooms.id,
                chatrooms.updated_at AS room_updated_at,
                messages.user_id AS message_user_id,
                messages.content,
                messages.created_at AS msg_created_at,
                messages.image")
  }

  scope :chatting_members, -> (user_id){ 
    where(
      chatroom_id: Member.where(user_id: user_id).select("chatroom_id")
    )
  }
end

app/models/message.rb
class Message < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  belongs_to :chatroom
  belongs_to :user

  validates :content, length: { maximum: 1000 }

  scope :recent_messages, -> (chatroom_id){
    where(chatroom_id: chatroom_id).order(:created_at).last(30)
  }
end

app/models/user.rb
class User < ApplicationRecord

  mount_uploader :photo, PhotoUploader

  has_secure_password
  has_many :messages, dependent: :destroy
  has_many :members, dependent: :destroy
  has_many :chatrooms

  validates :username, presence: true, uniqueness: { case_sensitive: false },
                        length: { minimum: 3, maximum: 15 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                      length: { maximum: 50},
                      format: { with: VALID_EMAIL_REGEX }
  
  def online?
    !Redis.new.get("user_#{self.id}_online").nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :require_user, :format_time
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end

  def format_time(created_at)
    created_at.in_time_zone.strftime('%b %-d　%k:%M')
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :require_user
  before_action :require_member, only: [:destroy]

  def index
    @chatrooms = Member.conversations.where(
      chatroom_id: Member.where(user_id: current_user.id).select("chatroom_id")
    ).where.not(user_id: current_user.id).order(room_updated_at: "DESC")
    @message = Message.new
  end

  def create
    @chatroom = Chatroom.new(creater_id: current_user.id)
    if @chatroom.save
      Member.create(chatroom_id: @chatroom.id, user_id: current_user.id)
      Member.create(chatroom_id: @chatroom.id, user_id: params[:chatroom][:user_id])
      RoomManagerJob.perform_later(@chatroom.id, format_time(@chatroom.created_at),
       params[:chatroom][:user_id], current_user)
    end
    redirect_to chatrooms_path
  end

  def destroy
    chatroom = Chatroom.find(params[:id])
    chatroom.destroy
    redirect_to chatrooms_path
  end

  private
  def chatroom_params
    params.require(:chatroom).permit(:user_id)
  end

  def require_member
    member = Member.find_by(user_id: current_user.id, chatroom_id: params[:id])
    unless !!member
      flash[:error] = "You can only delete your conversation"
      redirect_to root_path
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    message = Message.new(message_params)
    message.user = current_user
    chatroom = Chatroom.find_by(id: message.chatroom_id)
    return redirect_to chatrooms_path if chatroom.nil?

    if message.save!
      chatroom.update(last_message_id: message.id)
      ActionCable.server.broadcast "chatroom_#{message.chatroom_id}",
        message: message, message_time: format_time(message.created_at), 
        sender: current_user.username
      head :ok
    else 
      redirect_to chatrooms_path
    end
  end

  private
  def message_params
    params.require(:message).permit(:content, :chatroom_id, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      cookies.encrypted[:user_id] = user.id
      redirect_to chatrooms_path
    else
      flash.now[:error] = "There was something wrong with your login infomation"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    cookies.encrypted[:user_id] = nil
    flash[:success] = "You have successfully loged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, except: [:new, :create]
  before_action :set_user, only: [:update, :destroy]
  before_action :require_same_user, only: [:update, :destroy]

  def index
    @users = User.where.not(
      id: [ Member.chatting_members(current_user.id).select("user_id")]
    ).where.not(id: current_user.id)
    @chatroom = Chatroom.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to chatrooms_path
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your profile was successfully updated"
    else
      @user
    end
  end

  def destroy
    chatrooms = Chatroom.where(id: Member.where(user_id: @user.id).select("chatroom_id"))
    chatrooms.each do |chatroom|
      chatroom.destroy
    end
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :photo)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:error] = "You can only edit or delete your own account"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_helper.rb
module MessageHelper
  def latest_message(chatroom)
    if chatroom.content?
      chatroom.content
    else 
      chatroom.message_user_id == current_user.id ? 'you sent a image' : "#{chatroom.user.username} sent a image"
    end
  end

  def new_messages(chatroom_id)
    Message.recent_messages(chatroom_id)
  end
end

app/views/chatrooms/_conversation_list.html.erb
<% chatrooms.each.with_index(1) do |chatroom, idx| %>
  <a class="conversation item <% if idx == 1 %>active<% end %>" 
    data-tab="chatroom_<%= chatroom.id %>">
    <% if chatroom.user.photo? %>
      <%= image_tag chatroom.user.photo.url %>
    <% else %>
      <%= image_tag 'default-profile-photo.png' %>
    <% end %>
    <div class="title-text <%= 'online-color' if chatroom.user.online? %>" id="chat-user-<%= chatroom.user.id %>">
      <%= chatroom.user.username %>
      <input type="hidden" id="chatroom_idx_<%= idx %>" value="<%= chatroom.id %>">
    </div>
    <% if chatroom.content.present? || chatroom.image.present? %>
      <div class="created-date">
        <%= format_time(chatroom.msg_created_at) %>
      </div>
      <div class="conversation-message">
        <%= truncate(latest_message(chatroom), length: 30) %>
      </div>
    <% else %>
      <div class="created-date"></div>
      <div class="conversation-message"></div>
    <% end %>
  </a>
<% end %>

app/views/chatrooms/_delete_conversation_modal.html.erb
<div class="ui basic modal" id="deleteConversationModal">
  <div class="ui icon header">
    <i class="trash icon"></i>
    Delete Conversation
  </div>
  <div class="content">
    <p>Are you sure you want to delete this conversation? All messages within this conversation will be deleted.</p>
  </div>
  <div class="actions">
    <div class="ui red basic cancel inverted button">
      <i class="remove icon"></i>
      No
    </div>
    <%= link_to chatroom_path(chatroom != 'id' ? chatroom : 'id'), method: :delete,
      id: "deleteConvLink", class: "ui green ok inverted button" do %>
      <i class="checkmark icon"></i>
      Yes
    <% end %>
  </div>
</div>

app/views/chatrooms/_delete_user_modal.html.erb
<div class="ui basic modal" id="deleteUserModal">
  <div class="ui icon header">
    <i class="trash icon"></i>
    Delete Account
  </div>
  <div class="content">
    <p>Are you sure you want to delete your account?</p>
  </div>
  <div class="actions">
    <div class="ui red basic cancel inverted button">
      <i class="remove icon"></i>
      No
    </div>
    <%= link_to user_path(user), method: :delete, class: "ui green ok inverted button" do %>
      <i class="checkmark icon"></i>
      Yes
    <% end %>
  </div>
</div>

app/views/chatrooms/_message.html.erb
<% @chatrooms.each do |chatroom| %>
  <div class="ui tab" data-tab="chatroom_<%= chatroom.id %>">
    <% new_messages(chatroom.id).each do |message| %>
      <% if message.user_id == current_user.id %>
        <div class="message-row you-message">
          <div class="message-content">
            <%= render 'message_content', message: message %>
          </div>
        </div>
      <% else %>
        <div class="message-row other-message">
          <div class="message-content">
            <% if message.user.photo? %>
              <%= image_tag message.user.photo.url, size: '45x45', class: "other-photo"%>
            <% else %>
              <%= image_tag 'default-profile-photo.png', class: "other-photo"%>
            <% end %>
            <%= render 'message_content', message: message %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/chatrooms/_message_content.html.erb
<% if message.image? %>
  <div class="message-image">
    <%= image_tag message.image.url %>
  </div>
<% else %>
  <div class="message-text">
    <%= raw Rinku.auto_link(h(message.content), :all,'target="_blank"') %>
  </div>
<% end %>
<div class="message-time">
  <%= format_time(message.created_at) %>
</div>

app/views/chatrooms/_userInfoModal.html.erb
<div class="ui small modal" id="userInfoModal">
  <div class="header">
    <div class="content">Your Profile</div>
    <div class="ui positive right labeled icon button" id="editProfileBtn">
      Edit
      <i class="edit icon"></i>
    </div>
    <%= link_to do %>
      <div class="ui red right labeled icon button hidden-item">
        Cancel
        <i class="window close icon"></i>
      </div>
    <% end %>
  </div>
  <%= form_for user, html: { class: "ui profile image content form "} do |f| %>
    <div class="ui image">
      <% if user.photo? %>
        <%= image_tag user.photo.url, class: "ui circular profile image", id: "photoArea" %>
      <% else %>
        <%= image_tag 'default-profile-photo.png', class: "ui circular profile image", id: "photoArea" %>
      <% end %>
      <label class="change-photo-link hidden-item">Change Profile Photo
        <%= f.file_field :photo, accept: 'image/jpeg,image/gif,image/png', id: "photoLink" %>
      </label>
    </div>
    <div class="description">
      <div class="field">
        <label>Name</label>
        <%= f.text_field :username, placeholder: "Name", disabled: true %>
      </div>
      <div class="field">
        <label>Email</label>
        <%= f.email_field :email, placeholder: "E-mail address", disabled: true %>
      </div>
      <div class="field hidden-item">
        <label>Passwod</label>
        <div class="ui icon input">
          <%= f.password_field :password, class: "password", disabled: true %>
            <i id='eyeSlash' class="eye slash link icon"></i>
            <i id='eye' class="eye link icon"></i>
        </div>
      </div>
      <%= f.submit "Update", class: "ui button hidden-item", id: "updateBtn"%>
    </div>
  <% end %>
  <div class="actions">
    <div class="ui black deny button">
      Close
    </div>
  </div>
</div>

app/views/chatrooms/_user_info_modal.html.erb
<div class="ui small modal" id="userInfoModal">
  <div class="header">
    <div class="content">Your Profile</div>
    <div class="ui icon top left pointing dropdown" id="profileMenu">
      <i class="ellipsis vertical alternate icon"></i>
      <div class="menu">
        <div class="item" id="editProfile"><i class="edit right floated icon"></i>
        Edit Profile</div>
        <div class="item" id="deleteAccount"><i class="trash right floated icon"></i>
        Delete Account</div>
      </div>
    </div>
    <div class="ui red right labeled icon button hidden-item" id="cancelBtn">
      Cancel
      <i class="window close icon"></i>
    </div>
  </div>
  <%= form_for user, html: { class: "ui profile image content form "}, remote: true do |f| %>
    <div class="content-area">
      <div class="ui image">
        <% if user.photo? %>
          <%= image_tag user.photo.url, class: "ui circular profile image", id: "photoArea" %>
        <% else %>
          <%= image_tag 'default-profile-photo.png', class: "ui circular profile image", id: "photoArea" %>
        <% end %>
        <label class="change-photo-link hidden-item">Change Profile Photo
          <%= f.file_field :photo, accept: 'image/jpeg,image/gif,image/png', id: "photoLink" %>
        </label>
      </div>
      <div class="description">
        <div class="field">
          <label>Name</label>
          <%= f.text_field :username, placeholder: "Name", disabled: true %>
        </div>
        <div class="field">
          <label>Email</label>
          <%= f.email_field :email, placeholder: "E-mail address", disabled: true %>
        </div>
        <div class="field hidden-item">
          <label>Passwod</label>
          <div class="ui icon input">
            <%= f.password_field :password, class: "password", disabled: true %>
              <i id='eyeSlash' class="eye slash link icon"></i>
              <i id='eye' class="eye link icon"></i>
          </div>
        </div>
        <%= f.submit "Update", class: "ui button hidden-item", id: "updateBtn" %>
      </div>
    </div>
  <% end %>
  <div class="actions">
    <div class="ui black deny button">
      Close
    </div>
  </div>
</div>

app/views/chatrooms/index.html.erb
<div class="chat-container" id="chat-container">
  <div class="user-info-container">
    <div class="ui basic image label">
      <% if current_user.photo? %>
        <%= image_tag current_user.photo.url class: "ui image" %>
      <% else %>
        <%= image_tag 'default-profile-photo.png', class: "ui circular image" %>
      <% end %>
      <%= current_user.username %>
      <%= hidden_field_tag :currentUserId, current_user.id %>
    </div>
    <a>
      <span>
        <i class="info circle large icon"
          data-content="Account Info"></i>
      </span>
    </a>
    <%= link_to  logout_path, method: :delete do %>
      <span>
        <i class="sign out alternate large icon link" 
          data-content="Log out"></i>
      </span>
    <% end %>
  </div>
  <div class="conversation-list">
    <% if @chatrooms.present? %>
       <%= render 'conversation_list', chatrooms: @chatrooms %>
    <% end %>
  </div>
  <div class="new-message-container">
    <%= link_to users_path, class: "addModalBtn", remote: true do %>
      <i class="plus circle icon"></i>
    <% end %>
    <div class="new-message">New Conversation</div>
  </div>
  <div class="chat-title">
    <i class="angle left icon" id="leftIcon">
        <div class="msg-count"></div>
      </i>
    <span>
      <% if @chatrooms.present? %>
        <%= @chatrooms.first.user.username %>
      <% end %>
    </span>
    <div class="ui icon top left pointing dropdown" id="conversationMenu" <% if @chatrooms.blank? %>style="display:none"<% end %>>
      <i class="ellipsis vertical alternate icon"></i>
      <div class="menu">
        <div class="item" id="deleteConversation"><i class="trash right floated icon"></i>
        Delete Conversation</div>
      </div>
    </div>
  </div>
  <div class="chat-message-list">
    <% if @chatrooms.present? %>
      <%= render 'chatrooms/message', chatrooms: @chatrooms %>
    <% end %>
  </div>
  <%= form_for @message, url: messages_path, remote: true do |f| %>
    <label >
      <i class="images outline large icon"></i>
      <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', id: "imageIcon" %>
    </label>
    <%= f.text_area :content, placeholder: "send a message", rows: 1, maxlength: 1000 %>
    <% if @chatrooms.present? %>
      <%= f.hidden_field :chatroom_id, value: @chatrooms.first.id %>
    <% else %>
    <%= f.hidden_field :chatroom_id, value: "" %>
    <% end %>
    <%= f.submit id: "submitMessage", style: "display: none" %>
  <% end %>
</div>

<%= render 'user_info_modal', user: current_user %>
<%= render 'delete_user_modal', user: current_user %>
<% if @chatrooms.present? %>
  <%= render 'delete_conversation_modal', chatroom: @chatrooms.first %>
<% else %>
  <%= render 'delete_conversation_modal', chatroom: 'id' %>
<% end %>
<div class="ui modal" id="addModal"></div>

app/views/chatrooms/show.html.erb
<div class="chat-container">
  <div class="user-info-container">
    <div class="ui basic image label">
      <% if current_user.photo? %>
        <%= image_tag current_user.photo.url class: "ui image" %>
      <% else %>
        <%= image_tag 'default-profile-photo.png', class: "ui circular image" %>
      <% end %>
      <%= current_user.username %>
      <%= hidden_field_tag :currentUserId, current_user.id %>
    </div>
    <a>
      <span>
        <i class="info circle large icon"
          data-content="Account Info"></i>
      </span>
    </a>
    <%= link_to  logout_path, method: :delete do %>
      <span>
        <i class="sign out alternate large icon link" 
          data-content="Log out"></i>
      </span>
    <% end %>
  </div>
  <div class="conversation-list">
    <%= render 'conversation_list', chatrooms: @chatrooms %>
  </div>
  <div class="new-message-container">
    <%= link_to users_path, class: "addModalBtn", remote: true do %>
      <i class="plus circle icon"></i>
    <% end %>
    <div class="new-message">New Conversation</div>
  </div>
  <div class="chat-title">
    <span>
      <% if @chatrooms.present? %>
        <%= @chatrooms.first.user.username %>
      <% end %>
    </span>
    <div class="ui icon top left pointing dropdown">
      <i class="ellipsis vertical alternate icon"></i>
      <div class="menu">
        <div class="item"><i class="trash right floated icon"></i>
        Delete Conversation</div>
      </div>
    </div>
  </div>
  <div class="chat-message-list">
    <%= render 'chatrooms/message', chatrooms: @chatrooms %>
  </div>
  <%= form_for @message, url: messages_path, remote: true do |f| %>
    <label >
      <i class="images outline large icon"></i>
      <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', id: "imageIcon" %>
    </label>
    <%= f.text_area :content, placeholder: "send a message", rows: "1" %>
    <% if @chatrooms.present? %>
      <%= f.hidden_field :chatroom_id, value: @chatrooms.first.id %>
    <% end %>
    <%= f.submit id: "submitMessage", style: "display: none" %>
  </div>
  <% end %>
</div>

<%= render 'user_info_modal', user: @user %>
<div class="ui modal" id="addModal"></div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui compact <%= message_type %> message transition" id="infoMsg">
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <%= favicon_link_tag('favicon.ico') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= render 'layouts/messages'%>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="ui error message">
    <div class="header">
      There were some errors with your submission
    </div>
    <ul class="list">
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_addModal.html.erb
<div class="header">
  Find Users
</div>
<div class="content user-list">
  <% if users.count != 0 %>
    <div class="ui middle aligned divided list">
      <% users.each do |user| %>
        <div class="item">
          <div class="right floated content">
            <%= form_for chatroom, url: chatroom_path do |f| %>
              <%= f.hidden_field :user_id, value: user.id %>
              <%= button_tag type: "submit", class: "ui labeled icon button" do %>
                  <i class="comment outline icon"></i>Add
              <% end %>
            <% end %>
          </div>
          <% if user.photo? %>
            <%= image_tag user.photo.url, class: "ui avatar image" %>
          <% else %>
            <%= image_tag 'default-profile-photo.png', class: "ui avatar image" %>
          <% end %>
          <div class="content">
            <%= user.username%>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    There is no users to add
  <% end %>
</div>
<div class="actions">
  <div class="ui black deny button">
    Close
  </div>
</div>

app/views/users/_add_modal.html.erb
<div class="header">
  Find Users
</div>
<div class="content user-list">
  <% if users.count != 0 %>
    <div class="ui middle aligned divided list">
      <% users.each do |user| %>
        <div class="item">
          <div class="right floated content">
            <%= form_for chatroom, url: chatrooms_path do |f| %>
              <%= f.hidden_field :user_id, value: user.id %>
              <%= button_tag type: "submit", class: "ui labeled icon button" do %>
                  <i class="comment outline icon"></i>Talk
              <% end %>
            <% end %>
          </div>
          <% if user.photo? %>
            <%= image_tag user.photo.url, class: "ui avatar image" %>
          <% else %>
            <%= image_tag 'default-profile-photo.png', class: "ui avatar image" %>
          <% end %>
          <div class="content">
            <%= user.username%>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    There are no users to add
  <% end %>
</div>
<div class="actions">
  <div class="ui black deny button">
    Close
  </div>
</div>

app/views/users/index.js.erb
$('#addModal').html('<%=j render partial: 'add_modal', locals: {users: @users, chatroom: @chatroom} %>');

$('#addModal').modal('show');

app/views/users/new.html.erb
<%= form_for @user, html: {class: "login-box"} do |f| %>
    <h1>Sign Up</h1>
    <div class="textbox">
      <i class="user icon"></i>
      <%= f.text_field :username, placeholder: "Username" %>
    </div>
    <div class="textbox">
      <i class="envelope icon"></i>
      <%= f.email_field :email, placeholder: "E-mail address" %>
    </div>
    <div class="textbox">
      <i class="lock icon"></i>
      <%= f.password_field :password, class: "password", placeholder: "Password" %>
      <span class='eye-area'>
        <i id='eyeSlash' class="eye slash icon"></i>
        <i id='eye' class="eye icon"></i>
      </span>
    </div>
  
    <%= f.submit "Sign up", method: :post, class: "btn" %>
    <div class="buttom-text">
      You have already your accoount? <%= link_to 'Log in', root_path %>
    </div>
<% end %>
<div class="sign-up-errors">
  <%= render 'shared/errors', obj: @user %>
</div>

app/views/users/update.js.erb
$('#userInfoModal .error.message').remove();

$('#userInfoModal form').append('<%=j render partial: 'shared/errors', locals: { obj: @user } %>');

$('#userInfoModal .error.message').css('display', 'block');